name: Build
on:
  push:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: Bootstrap vcpkg
        run: 'cd vendor/vcpkg && ./bootstrap-vcpkg.sh'
      - name: Set VCPKG_ROOT
        run: echo "VCPKG_ROOT=$GITHUB_WORKSPACE/vendor/vcpkg" >> $GITHUB_ENV
      - name: Update CMakeUserPresets.json
        run: sed -i "s|REPLACE_WITH_VCPKG_ROOT|$VCPKG_ROOT|g" CMakeUserPresets.json
      - name: Update PATH
        run: echo "PATH=$VCPKG_ROOT:$PATH" >> $GITHUB_ENV
      - name: Install dependencies
        run: 'sudo apt install -y gcovr nlohmann-json3-dev'
      - name: Configure CMake
        run: 'cmake --preset=github'
      - name: Configure
        run: 'cmake -B build'
      - name: Build
        run: 'cmake --build build'
      - name: Execute
        run: './build/boson'
      - name: Run tests
        run: 'cp CTestCustom.cmake build && cd build && ctest -T Test -T Coverage && cd ../'
      - name: Generate Cobertura report
        run: 'gcovr --cobertura build/coverage.xml --exclude build/vcpkg_installed'
      - name: Code coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: Bootstrap vcpkg
        run: 'cd vendor/vcpkg && ./bootstrap-vcpkg.sh'
      - name: Set VCPKG_ROOT
        run: echo "VCPKG_ROOT=$GITHUB_WORKSPACE/vendor/vcpkg" >> $GITHUB_ENV
      - name: Update CMakeUserPresets.json
        run: sed -i '' "s|REPLACE_WITH_VCPKG_ROOT|$VCPKG_ROOT|g" CMakeUserPresets.json
      - name: Update PATH
        run: echo "PATH=$VCPKG_ROOT:$PATH" >> $GITHUB_ENV
      - name: Install dependencies
        run: 'brew install imagemagick inkscape'
      - name: Configure CMake
        run: 'cmake --preset=github'
      - name: Configure
        run: 'cmake -B build'
      - name: Build
        run: 'cmake --build build'
      - name: Execute
        run: './build/boson'
      - name: Create macOS application directory
        run: 'mkdir -p build/files/Boson.app/Contents/Resources build/files/Boson.app/Contents/MacOS'
      - name: Copy macOS application binary
        run: |
          cp build/boson build/files/Boson.app/Contents/MacOS/Boson
          cp resources/macos/Info.plist build/files/Boson.app/Contents/
      - name: Create macOS application icon
        run: |
          mkdir -p build/files/Boson.iconset
          inkscape -w 1024 -o build/files/Boson.iconset/icon_512x512@2x.png resources/shared/icon.svg
          magick build/files/Boson.iconset/icon_512x512@2x.png -resize 512 build/files/Boson.iconset/icon_512x512.png
          cp build/files/Boson.iconset/icon_512x512.png build/files/Boson.iconset/icon_256x256@2x.png
          magick build/files/Boson.iconset/icon_512x512@2x.png -resize 256 build/files/Boson.iconset/icon_256x256.png
          cp build/files/Boson.iconset/icon_256x256.png build/files/Boson.iconset/icon_128x128@2x.png
          magick build/files/Boson.iconset/icon_512x512@2x.png -resize 128 build/files/Boson.iconset/icon_128x128.png
          magick build/files/Boson.iconset/icon_512x512@2x.png -resize 64 build/files/Boson.iconset/icon_32x32@2x.png
          magick build/files/Boson.iconset/icon_512x512@2x.png -resize 32 build/files/Boson.iconset/icon_32x32.png
          cp build/files/Boson.iconset/icon_32x32.png build/files/Boson.iconset/icon_16x16@2x.png
          magick build/files/Boson.iconset/icon_512x512@2x.png -resize 16 build/files/Boson.iconset/icon_16x16.png
          iconutil -c icns build/files/Boson.iconset
          cp build/files/Boson.icns build/files/Boson.app/Contents/Resources
          rm -rf build/files/Boson.iconset
          rm build/files/Boson.icns
      - name: Upload macOS application bundle
        uses: actions/upload-artifact@v7
        with:
          name: Boson
          path: build/files/
  build-steamrt4:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/steamrt4/sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: Bootstrap vcpkg
        run: 'cd vendor/vcpkg && ./bootstrap-vcpkg.sh'
      - name: Set VCPKG_ROOT
        run: echo "VCPKG_ROOT=$GITHUB_WORKSPACE/vendor/vcpkg" >> $GITHUB_ENV
      - name: Update CMakeUserPresets.json
        run: sed -i "s|REPLACE_WITH_VCPKG_ROOT|$VCPKG_ROOT|g" CMakeUserPresets.json
      - name: Update PATH
        run: echo "PATH=$VCPKG_ROOT:$PATH" >> $GITHUB_ENV
      - name: Configure CMake
        run: 'cmake --preset=github'
      - name: Configure
        run: 'cmake -B build'
      - name: Build
        run: 'cmake --build build'
      - name: Execute
        run: './build/boson'
  build-flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        run: 'sudo apt update && sudo apt install -y flatpak flatpak-builder'
      - name: Add Flathub repository
        run: 'flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo'
      - name: Build Flatpak
        run: |
          mkdir -p build/files/share/applications/ build/files/share/icons/hicolor/scalable/apps/
          cp resources/shared/icon.svg build/files/share/icons/hicolor/scalable/apps/tv.kenley.boson.Boson.svg
          cp resources/linux/boson.desktop build/files/share/applications/tv.kenley.boson.Boson.desktop
          flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo --install build resources/linux/tv.kenley.boson.Boson.yml --disable-rofiles-fuse
      - name: Execute
        run: 'flatpak run tv.kenley.boson.Boson'
      - name: Build single-file bundle
        run: 'flatpak build-bundle repo boson.flatpak tv.kenley.boson.Boson --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo'
      - name: Upload Flatpak
        uses: actions/upload-artifact@v7
        with:
          name: Flatpak
          path: boson.flatpak
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: Bootstrap vcpkg
        run: 'cd vendor/vcpkg && ./bootstrap-vcpkg.sh'
      - name: Set VCPKG_ROOT
        run: echo "VCPKG_ROOT=$(pwd)/vendor/vcpkg" >> $GITHUB_ENV
      - name: Set CMAKE_MAKE_PROGRAM
        run: echo "CMAKE_MAKE_PROGRAM=$(which ninja)" >> $GITHUB_ENV
      - name: Update PATH to include vcpkg
        run: echo "PATH=$VCPKG_ROOT:$PATH" >> $GITHUB_ENV
      - name: Update PATH to include mingw64
        run: echo "PATH=$PATH:C:\msys64\mingw64\bin" >> $GITHUB_ENV
      - name: Update PATH to include PowerShell
        run: echo "C:\Windows\System32\WindowsPowerShell\v1.0" >> $GITHUB_PATH
      - name: Update PATH to include dumpbin
        run: echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\17.14.37301.10\bin\Hostx64\x64" >> $GITHUB_PATH
      - name: Print MSVC location
        run: dir C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC
        shell: cmd
      - name: Set CC
        run: echo "CC=$(which clang)" >> $GITHUB_ENV
      - name: Set CXX
        run: echo "CXX=$(which clang)" >> $GITHUB_ENV
      - name: Set RC
        run: echo "RC=C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64\rc.exe" >> $GITHUB_ENV
      - name: Update CMakeUserPresets.json
        run: |
          sed -i "s|REPLACE_WITH_VCPKG_ROOT|$VCPKG_ROOT|g" CMakeUserPresets.json
          sed -i "s|REPLACE_WITH_NINJA_PATH|$CMAKE_MAKE_PROGRAM|g" CMakeUserPresets.json
      - name: Configure CMake
        run: 'cmake --preset=github-windows -DCMAKE_MAKE_PROGRAM=$CMAKE_MAKE_PROGRAM -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake'
      - name: Configure
        run: 'cmake -B build'
      - name: Build
        run: 'cmake --build build'
      - name: Execute
        run: './build/boson'
      - name: Upload build output
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build