name: Build
on:
  push:
    branches:
      - main
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/steamrt4/sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print ldd version
        run: 'ldd --version'
